name: teste
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.1
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  collection: ^1.15.0
  excel: ^2.0.0-null-safety-3
  mongo_dart: ^0.7.1
